In [16]:
import pandas as pd

chunk_size = 100000  # Adjust based on your available memory
chunks = []

for chunk in pd.read_csv("business_collection.csv", dtype=str, chunksize=chunk_size, low_memory=False):
    chunks.append(chunk)

df = pd.concat(chunks)

ParserError: Error tokenizing data. C error: out of memory

In [2]:
df.head()

,_id,Business Name,Origin URL,Company URL,Address,State,City,Phone,Contact Person,Categories
0,67a0e3cc788a7c5be6c226be,Altagas Ltd,https://ab.allpages.com/acadia-valley/communit...,https://listings.allpages.com/ab-E7F0003685-ac...,"Acadia Valley, AB T0J0A0",AB,Acadia Valley,(403) 972-3960,NaN,Gas Companies
1,67a0e3cc788a7c5be6c226bf,Atb Agency,https://ab.allpages.com/acadia-valley/finance/...,https://listings.allpages.com/ab-0001803275-ac...,"PO Box 93, Acadia Valley, AB T0J0A0",AB,Acadia Valley,(403) 972-3805,NaN,Banks
2,67a0e3cc788a7c5be6c226c0,Prairie Elevator,https://ab.allpages.com/acadia-valley/agricult...,https://listings.allpages.com/ab-0001404754-ac...,"Acadia Valley, AB T0J0A0",AB,Acadia Valley,(403) 972-2028,NaN,Grain Elevators
3,67a0e3cc788a7c5be6c226c1,Atb Financial Agency,https://ab.allpages.com/acadia-valley/finance/...,https://listings.allpages.com/ab-0001877516-ac...,"Acadia Valley, AB T0J",AB,Acadia Valley,(403) 972-2263,NaN,Financial Services
4,67a0e3cc788a7c5be6c226c2,Municipal District Of Acadia No 34 - Fire Depa...,https://ab.allpages.com/acadia-valley/communit...,https://listings.allpages.com/ab-A4K0013873-ac...,"Acadia Valley, AB T0J",AB,Acadia Valley,(403) 972-2111,NaN,Fire Department

In [3]:
df = df.drop(columns=['Contact Person'])

In [4]:
print(df.columns)

Index(['_id', 'Business Name', 'Origin URL', 'Company URL', 'Address', 'State',
       'City', 'Phone', 'Categories'],
      dtype='object')

In [5]:
df.head()

,_id,Business Name,Origin URL,Company URL,Address,State,City,Phone,Categories
0,67a0e3cc788a7c5be6c226be,Altagas Ltd,https://ab.allpages.com/acadia-valley/communit...,https://listings.allpages.com/ab-E7F0003685-ac...,"Acadia Valley, AB T0J0A0",AB,Acadia Valley,(403) 972-3960,Gas Companies
1,67a0e3cc788a7c5be6c226bf,Atb Agency,https://ab.allpages.com/acadia-valley/finance/...,https://listings.allpages.com/ab-0001803275-ac...,"PO Box 93, Acadia Valley, AB T0J0A0",AB,Acadia Valley,(403) 972-3805,Banks
2,67a0e3cc788a7c5be6c226c0,Prairie Elevator,https://ab.allpages.com/acadia-valley/agricult...,https://listings.allpages.com/ab-0001404754-ac...,"Acadia Valley, AB T0J0A0",AB,Acadia Valley,(403) 972-2028,Grain Elevators
3,67a0e3cc788a7c5be6c226c1,Atb Financial Agency,https://ab.allpages.com/acadia-valley/finance/...,https://listings.allpages.com/ab-0001877516-ac...,"Acadia Valley, AB T0J",AB,Acadia Valley,(403) 972-2263,Financial Services
4,67a0e3cc788a7c5be6c226c2,Municipal District Of Acadia No 34 - Fire Depa...,https://ab.allpages.com/acadia-valley/communit...,https://listings.allpages.com/ab-A4K0013873-ac...,"Acadia Valley, AB T0J",AB,Acadia Valley,(403) 972-2111,Fire Department

In [6]:
df = df.drop_duplicates()

In [7]:
df.describe()

Dask DataFrame Structure:
                  _id Business Name Origin URL Company URL Address   State    City   Phone Categories
npartitions=1
               object        object     object      object  object  object  object  object     object
                  ...           ...        ...         ...     ...     ...     ...     ...        ...
Dask Name: concat, 23 expressions
Expr=Concat(frames=[((DropDuplicates(frame=Drop(frame=ArrowStringConversion(frame=FromMapProjectable(449847e)), columns=['Contact Person'])))['_id']).describenonnumeric(split_every=False), ((DropDuplicates(frame=Drop(frame=ArrowStringConversion(frame=FromMapProjectable(449847e)), columns=['Contact Person'])))['Business Name']).describenonnumeric(split_every=False), ((DropDuplicates(frame=Drop(frame=ArrowStringConversion(frame=FromMapProjectable(449847e)), columns=['Contact Person'])))['Origin URL']).describenonnumeric(split_every=False), ((DropDuplicates(frame=Drop(frame=ArrowStringConversion(frame=FromMapProjectable(449847e)), columns=['Contact Person'])))['Company URL']).describenonnumeric(split_every=False), ((DropDuplicates(frame=Drop(frame=ArrowStringConversion(frame=FromMapProjectable(449847e)), columns=['Contact Person'])))['Address']).describenonnumeric(split_every=False), ((DropDuplicates(frame=Drop(frame=ArrowStringConversion(frame=FromMapProjectable(449847e)), columns=['Contact Person'])))['State']).describenonnumeric(split_every=False), ((DropDuplicates(frame=Drop(frame=ArrowStringConversion(frame=FromMapProjectable(449847e)), columns=['Contact Person'])))['City']).describenonnumeric(split_every=False), ((DropDuplicates(frame=Drop(frame=ArrowStringConversion(frame=FromMapProjectable(449847e)), columns=['Contact Person'])))['Phone']).describenonnumeric(split_every=False), ((DropDuplicates(frame=Drop(frame=ArrowStringConversion(frame=FromMapProjectable(449847e)), columns=['Contact Person'])))['Categories']).describenonnumeric(split_every=False)], axis=1)

In [10]:
# Verify the column is gone
print(df.columns)  # Should NOT include 'Contact Person'

Index(['_id', 'Business Name', 'Origin URL', 'Company URL', 'Address', 'State',
       'City', 'Phone', 'Categories'],
      dtype='object')

In [12]:
# Convert all columns to string
df = df.astype(str)

In [13]:

df.to_csv("cleaned_file.csv", index=False)

ValueError: Mismatched dtypes found in `pd.read_csv`/`pd.read_table`.

+----------------+--------+----------+
| Column         | Found  | Expected |
+----------------+--------+----------+
| Contact Person | object | float64  |
+----------------+--------+----------+

The following columns also raised exceptions on conversion:

- Contact Person
  ValueError("could not convert string to float: 'Morris Tyson (Manager)'")

Usually this is due to dask's dtype inference failing, and
*may* be fixed by specifying dtypes manually by adding:

dtype={'Contact Person': 'object'}

to the call to `read_csv`/`read_table`.